name: ntfy

include:
  - ext/docker-compose-snippets/tailscale-caddy.yaml
  - ext/docker-compose-snippets/simple-reverse-proxy.yaml

services:
  ntfy:
    image: binwiederhier/ntfy:latest
    command:
      - serve
    volumes:
      - ntfy_cache:/var/cache/ntfy
    environment:
      NTFY_BASE_URL: https://ntfy.ipn.rahulsalvi.com
      NTFY_LISTEN_HTTP: "127.0.0.1:8080"
      NTFY_CACHE_FILE: /var/cache/ntfy/cache.db
      NTFY_BEHIND_PROXY: true
      NTFY_ATTACHMENT_CACHE_DIR: /var/cache/ntfy/attachments
    healthcheck: # optional: remember to adapt the host:port to your environment
      test:
        [
          "CMD-SHELL",
          "wget -q --tries=1 http://localhost:8080/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1",
        ]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    extends:
      file: ext/docker-compose-snippets/tailscale-app-base.yaml
      service: tailscale-app-base

volumes:
  ntfy_cache:

secrets:
  ts_authkey:
    file: ./ts_authkey.txt
